### ISSUE TITLE
default config with otlp exporter silently fails

### ISSUE THREAD

**Issue by abraxxa** [jjatria/perl-opentelemetry-sdk#18]
Reading the comments of https://github.com/jjatria/perl-opentelemetry-sdk/issues/5#issuecomment-1821724308 and adding
`use Log::Any::Adapter 'Stderr';
use Metrics::Any::Adapter 'Stderr';` to my code showed that OpenTelemetry::Exporter::OTLP can't be loaded because it's a separate CPAN dist:
`Error configuring 'otlp' span processor: Can't locate OpenTelemetry/Exporter/OTLP.pm in @INC (you may need to install the OpenTelemetry::Exporter::OTLP module) (@INC entries checked: lib /home/ahartmai/.plenv/versions/5.40.0/lib/perl5/site_perl/5.40.0/x86_64-linux /home/ahartmai/.plenv/versions/5.40.0/lib/perl5/site_perl/5.40.0 /home/ahartmai/.plenv/versions/5.40.0/lib/perl5/5.40.0/x86_64-linux /home/ahartmai/.plenv/versions/5.40.0/lib/perl5/5.40.0) at /home/ahartmai/.plenv/versions/5.40.0/lib/perl5/site_perl/5.40.0/Module/Runtime.pm line 314.`

OpenTelemetry::SDK should at least warn if not die with that message.

The documentation really needs a `Getting started` section too...

**Comment by abraxxa** [comment]
I see...
So the exporter(s) are configured (using env vars) but can't be changed after startup, right?
If this is the case I'd opt for _fail fast_ at startup.

As for the logging of such _fast fail_ messages I'd not use any logger for them but a regular die.

**Comment by jjatria** [comment]
> The documentation really needs a Getting started section too...

I've started adding some of this: see [OpenTelemetry::Guides::Quickstart](https://github.com/jjatria/perl-opentelemetry/blob/main/lib/OpenTelemetry/Guides/Quickstart.pod) (not on CPAN yet). It's based on the existing OpenTelemetry guides for similar languages (looking at [Ruby in particular](https://opentelemetry.io/docs/languages/ruby/getting-started/), since this implementation borrows a lot from that one). Might not be the most helpful, but it's a start. I'd welcome any comments on what it should include, and what it might be missing!

**Comment by jjatria** [comment]
Back to the core issue, though, I think the exporter might have to be a core dependency. If we're going to have a default exporter, then it doesn't make much sense for the SDK not to include that exporter. Otherwise, we're just setting people up for failure. The OTLP exporter distribution is already "safe" in the sense that it doesn't _require_ the protobuf libraries, which are sometimes a little tricky to install, but will use them if they are available. This was not the case initially, which is why it's a different distribution.

If we do that (support the default configuration ... by default, which seems obvious in hindsight), then I agree that failing fast is probably the right thing to do.

**Comment by abraxxa** [comment]
Thanks for starting the Quckstart docs! 🎉 

Having a default exporter sounds very good as well! 👍🏻

**Comment by jjatria** [comment]
@abraxxa I've made a PR that should address this. Would you mind taking a look to see if that does what you would expect?

**Comment by jjatria** [comment]
Version 0.025, now on CPAN, adds the OTLP exporter as a dependency and dies if it encounters an error during import.
